image: php:7.3

before_script:
  - apt-get update -qq
  - apt-get install -y -qq git

deploy to heroku:
  stage: deploy
  script:
    - apt-get install -y ruby
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
    - heroku run php artisan migrate
    - heroku run php artisan db:seed
    - heroku run php artisan module:seed
  only:
    - master
