image: php:7.3

before_script:
  - apt-get update -qq
  - apt-get install -y -qq git

deploy to heroku:
  stage: deploy
  script:
    - apt-get install -y ruby
    - apt-get install -y vim
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_PRODUCTION --api-key=$HEROKU_API_KEY
  only:
    - test
