site_name: Documentación de Usuario.
nav:
      - Inicio: index.md
      - Acerca de: about.md
      - Gestión de Proyecto: development_methodology.md
      - Información General: information.md
      - Instalación: installation.md   
      - Configuración: 
        - Configuración: setting/setting.md 
        - Configuración General: setting/general_setting.md
        - Configuración de Acceso: setting/access_setting.md
        - Configuración de Módulos: setting/modules_setting.md
      - Panel de Control: 
        - Panel de Control: control_panel/control_panel.md 
        - Herramientas para Desarrolladores: control_panel/developers.md 
        - Control de Acceso: control_panel/access_control.md
        - Módulo de Contabilidad: control_panel/accounting_module.md
        - Módulo de Bienes: control_panel/asset_module.md 
        - Módulo de Almacén: control_panel/warehouse_module.md
      - Preguntas Frecuentes: 
        - Preguntas Frecuentes: frequent_questions/frequent_questions.md  
        

    
# Project information
site_description: A Material Design theme for MkDocs
# site_author: 
# site_url:

# # Repository
# repo_name: 
# repo_url: 


# Copyright
# copyright: ''

# Configuration
theme:
  name: null
  custom_dir: ../material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: blue
    accent:  blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png  

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
# extra:
#   social:
#     - type: globe
#       link: 
#     - type: github-alt
#       link: 
#     - type: twitter
#       link: 
#     - type: linkedin
#       link: 











            

