site_name: Documentación de Usuario.
nav:
      - Módulo de Atención al Ciudadano: index.md
      - Solicitudes: requests.md
      - Reportes: reports.md
      - Ingresar Cronograma: schedule.md
      - Configuración: 
        - Formatos de Códigos: setting/code_format.md 
        - Registros Comúnes: setting/common_records.md
      - Panel de Control: 
        - Panel de Control: control_panel/control_panel.md 
      - Preguntas Frecuentes: 
        - Preguntas Frecuentes: frequent_questions/frequent_questions.md  
      

    
# Project information
site_description: A Material Design theme for MkDocs
# site_author: 
# site_url: 

# # Repository
# repo_name: 
# repo_url: 


# Copyright
# copyright: ''

# Configuration
theme:
  name: null
  custom_dir: ../material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: blue
    accent:  blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.png  

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
# extra:
#   social:
#     - type: globe
#       link: 
#     - type: github-alt
#       link: 
#     - type: twitter
#       link: 
#     - type: linkedin
#       link: 











            

