# Project information
site_name: Documentación de Usuario.

# Page tree
nav:
      - Inicio: index.md
      #- Módulo de Bienes:
      #  - Registros: registers.md
      # - Asignaciones: assignments.md
      #  - Desincorporaciones: disincorporations.md
      #  - Solicitudes: requests.md
      #  - Historial de Inventario: inventory_history.md
      #  - Reportes: reports.md
      #- Configuración: 
      #  - Formato de Códigos: setting/code_format.md
      #  - Parámetros Generales: setting/general_parameters.md
      #  - Parámetros Específicos: setting/specific_parameters.md 
      #- Panel de Control: 
      #  - Panel de Control: control_panel/control_panel.md 
      #- Preguntas Frecuentes: frequent_questions.md  

# Repository
repo_name: Repositorio-Kavac
repo_url: https://tibisay.cenditel.gob.ve/sistema-de-gestion/

# Configuration
theme:
  name: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    #- navigation.instant
  palette:
    scheme: default
    # primary: light-blue
    accent: light-blue
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/favicon.png
  logo: images/logo.png
  icon: 
    repo: fontawesome/brands/git-square 
  
          
# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
# extra:
#   social:
#     - icon: 
#       link: 

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details

# css additional
extra_css:
  - stylesheets/extra.css








            

